allowBuilds:
  msw: false
minimumReleaseAge: 4320
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.23
  vite-plus: 0.1.23
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.23
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
