#!/usr/bin/env bash
#MISE description="Start the backend dev server and restart on source changes"
#MISE depends=["build:frontend"]
set -euo pipefail
air -c .air.toml -- start --foreground --debug --log-level debug
