package selftelemetry

import (
	"context"
	"errors"
	"time"

	"go.opentelemetry.io/collector/pdata/plog"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/pdata/ptrace"
	"go.opentelemetry.io/contrib/instrumentation/runtime"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	sdklog "go.opentelemetry.io/otel/sdk/log"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
)

// InternalResourceAttribute marks telemetry generated by otelop's own SDK.
// Storage tracing uses it to suppress instrumentation while ingesting those
// traces, preventing storage spans from recursively generating more storage
// spans forever.
const InternalResourceAttribute = "otelop.telemetry.internal"

const (
	durationHistogramMaxSize  = 160
	durationHistogramMaxScale = 20
)

type suppressTracingKey struct{}

// SuppressTracing marks asynchronous work that is ingesting otelop's own
// telemetry. Instrumentation still performs the work but must not emit spans,
// otherwise those spans re-enter the same pipeline indefinitely.
func SuppressTracing(ctx context.Context) context.Context {
	return context.WithValue(ctx, suppressTracingKey{}, true)
}

// TracingSuppressed reports whether instrumentation should remain silent.
func TracingSuppressed(ctx context.Context) bool {
	suppressed, _ := ctx.Value(suppressTracingKey{}).(bool)
	return suppressed
}

// TracesAreInternal reports whether every resource in a trace batch came
// from otelop's self-telemetry SDK.
func TracesAreInternal(td ptrace.Traces) bool {
	resources := td.ResourceSpans()
	if resources.Len() == 0 {
		return false
	}
	for i := 0; i < resources.Len(); i++ {
		value, ok := resources.At(i).Resource().Attributes().Get(InternalResourceAttribute)
		if !ok || !value.Bool() {
			return false
		}
	}
	return true
}

// MetricsAreInternal is TracesAreInternal for metric batches.
func MetricsAreInternal(md pmetric.Metrics) bool {
	resources := md.ResourceMetrics()
	if resources.Len() == 0 {
		return false
	}
	for i := 0; i < resources.Len(); i++ {
		value, ok := resources.At(i).Resource().Attributes().Get(InternalResourceAttribute)
		if !ok || !value.Bool() {
			return false
		}
	}
	return true
}

// LogsAreInternal is TracesAreInternal for log batches.
func LogsAreInternal(ld plog.Logs) bool {
	resources := ld.ResourceLogs()
	if resources.Len() == 0 {
		return false
	}
	for i := 0; i < resources.Len(); i++ {
		value, ok := resources.At(i).Resource().Attributes().Get(InternalResourceAttribute)
		if !ok || !value.Bool() {
			return false
		}
	}
	return true
}

// Result holds the providers created by Setup.
type Result struct {
	LoggerProvider *sdklog.LoggerProvider
	Shutdown       func(context.Context) error
}

// Setup initializes OTel SDK providers that export telemetry back to
// otelop's own OTLP gRPC endpoint.
func Setup(ctx context.Context, endpoint string) (*Result, error) {
	res, err := newResource(ctx)
	if err != nil {
		return nil, err
	}

	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{},
		propagation.Baggage{},
	))

	// TracerProvider
	traceExp, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(endpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(traceExp),
		sdktrace.WithResource(res),
	)
	otel.SetTracerProvider(tp)

	// MeterProvider
	metricExp, err := otlpmetricgrpc.New(ctx,
		otlpmetricgrpc.WithEndpoint(endpoint),
		otlpmetricgrpc.WithInsecure(),
		otlpmetricgrpc.WithTemporalitySelector(selfTelemetryTemporality),
	)
	if err != nil {
		return nil, err
	}

	mp := sdkmetric.NewMeterProvider(
		sdkmetric.WithReader(sdkmetric.NewPeriodicReader(metricExp,
			sdkmetric.WithInterval(10*time.Second),
		)),
		sdkmetric.WithResource(res),
		sdkmetric.WithView(durationHistogramView()),
	)
	otel.SetMeterProvider(mp)

	// LoggerProvider
	logExp, err := otlploggrpc.New(ctx,
		otlploggrpc.WithEndpoint(endpoint),
		otlploggrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}

	lp := sdklog.NewLoggerProvider(
		sdklog.WithProcessor(sdklog.NewBatchProcessor(logExp)),
		sdklog.WithResource(res),
	)

	// Go runtime metrics (memory, GC, goroutines, etc.)
	if err := runtime.Start(); err != nil {
		return nil, err
	}

	return &Result{
		LoggerProvider: lp,
		Shutdown: func(ctx context.Context) error {
			return errors.Join(tp.Shutdown(ctx), mp.Shutdown(ctx), lp.Shutdown(ctx))
		},
	}, nil
}

// selfTelemetryTemporality exports duration histograms as independent
// collection intervals. This avoids deriving deltas from cumulative
// exponential histograms whose scale can change as their value range grows.
// Other instrument kinds retain the SDK's cumulative default.
func selfTelemetryTemporality(kind sdkmetric.InstrumentKind) metricdata.Temporality {
	if kind == sdkmetric.InstrumentKindHistogram {
		return metricdata.DeltaTemporality
	}
	return sdkmetric.DefaultTemporalitySelector(kind)
}

// durationHistogramView keeps latency resolution proportional across values
// from sub-millisecond queries through multi-second storage work. The SDK's
// default explicit boundaries are unit-agnostic, so a seconds instrument
// would otherwise put every value below five seconds into one bucket.
func durationHistogramView() sdkmetric.View {
	return sdkmetric.NewView(
		sdkmetric.Instrument{
			Name: "otelop.*.duration",
			Kind: sdkmetric.InstrumentKindHistogram,
			Unit: "s",
		},
		sdkmetric.Stream{
			Aggregation: sdkmetric.AggregationBase2ExponentialHistogram{
				MaxSize:  durationHistogramMaxSize,
				MaxScale: durationHistogramMaxScale,
			},
		},
	)
}

func newResource(ctx context.Context) (*resource.Resource, error) {
	return resource.New(ctx,
		resource.WithAttributes(
			semconv.ServiceName("otelop"),
			attribute.Bool(InternalResourceAttribute, true),
		),
	)
}
